name: Azure Static Web Apps CI/CD

# Only trigger on pushes or PRs targeting master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    # Only run for pushes or PRs to master
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Setup Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build for live environment
      - name: Build for Live
        run: npm run build:live

      # Deploy to Azure
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_ROCK_0BD3EA100 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          output_location: "dist" # Must match build folder
          skip_app_build: true


